### ISSUE TITLE
'mlir-c/AffineExpr.h' file not found when `mix test`

### ISSUE THREAD

**Issue by kianmeng** [beaver-lodge/beaver#180]
Environment:

Ubuntu: 22.10
Zig: 0.10.1 (`snap install zig --classic --beta`)

Steps to reproduce:

```sh
$ git clone https://github.com/beaver-lodge/beaver.git
$ cd beaver
$ mix deps.get
$ mix test
...
12:57:17.440 [debug] [Kinda] generating Zig code for wrapper: /tmp/beaver/native/mlir-c/include/mlir-c/Beaver/wrapper.h
/tmp/beaver/native/mlir-c/include/mlir-c/Beaver/wrapper.h:1:10: 'mlir-c/AffineExpr.h' file not found

== Compilation error in file lib/beaver/mlir/capi.ex ==
** (RuntimeError) fail to run zig translate-c for wrapper: /tmp/beaver/native/mlir-c/include/mlir-c/Beaver/wrapper.h
    (kinda 0.2.12) lib/codegen/wrapper.ex:140: Kinda.CodeGen.Wrapper.gen_and_build_zig/2
    (kinda 0.2.12) lib/prebuilt.ex:234: Kinda.Prebuilt.__using__/2
    lib/beaver/mlir/capi.ex:21: (module)
```

```sh
$ apt-file search mlir-c/AffineExpr.h
libmlir-13-dev: /usr/lib/llvm-13/include/mlir-c/AffineExpr.h
libmlir-14-dev: /usr/lib/llvm-14/include/mlir-c/AffineExpr.h
libmlir-15-dev: /usr/lib/llvm-15/include/mlir-c/AffineExpr.h

$ dpkg-query -S /usr/lib/llvm-15/include/mlir-c/AffineExpr.h
libmlir-15-dev:amd64: /usr/lib/llvm-15/include/mlir-c/AffineExpr.h
```

**Comment by jackalcooper** [comment]
You might need to build LLVM from a very recent version, main branch of the commit in https://github.com/beaver-lodge/beaver/blob/main/LLVM_COMMIT

**Comment by jackalcooper** [comment]
More detailed steps to setup the dev env is in the "Development" section of readme, link: https://github.com/beaver-lodge/beaver#development
