### ISSUE TITLE
Example in `Your first compiler with Beaver!` unrunable

### ISSUE THREAD

**Issue by glyh** [beaver-lodge/beaver#196]
I tried the following codes in iex:
```elixir
Mix.install([
  {:beaver, "~> 0.2"}
])

use Beaver

# Copied from https://github.com/beaver-lodge/beaver/blob/main/test/gen_ir_test.exs
# use Beaver.Case, async: true
# use Beaver
alias Beaver.MLIR
alias Beaver.MLIR.{Attribute, Type}
alias Beaver.MLIR.Dialect.{Func, Arith, CF}
require Func
# ----

ctx = MLIR.Context.create()

ir =
  mlir ctx: ctx do
    module do
      Func.func some_func(function_type: Type.function([Type.i32()], [Type.i32()])) do
        region do
          block bb_entry(a >>> Type.i32()) do
            b = Arith.constant(value: Attribute.integer(Type.i32(), 1024)) >>> Type.i32()
            c = Arith.addi(a, b) >>> Type.i32()
            Func.return(c) >>> []
          end
        end
      end
    end
  end

import MLIR.Conversion

llvm_ir =
  ir
  |> convert_arith_to_llvm
  |> MLIR.Pass.Composer.nested("func.func", fn pm ->
    MLIR.Pass.pipeline!(pm, "func.func(llvm-request-c-wrappers)")
  end)
  |> convert_func_to_llvm
  |> MLIR.Pass.Composer.run!()

```
It yields error:
```
** (FunctionClauseError) no function clause matching in Beaver.MLIR.Pass.Composer.create_pass/1    
    
    The following arguments were given to Beaver.MLIR.Pass.Composer.create_pass/1:
    
        # 1
        #Function<42.3316493/1 in :erl_eval.expr/6>
    
    Attempted function clauses (showing 3 out of 3):
    
        defp create_pass(pass_module) when is_atom(pass_module)
        defp create_pass(%Beaver.MLIR.Pass{} = pass)
        defp create_pass({argument, op, run}) when is_bitstring(op) and is_function(run)
    
    (beaver 0.2.19) lib/beaver/mlir/pass/composer.ex:34: Beaver.MLIR.Pass.Composer.create_pass/1
    (beaver 0.2.19) lib/beaver/mlir/pass/composer.ex:87: Beaver.MLIR.Pass.Composer.add_pass/2
    (beaver 0.2.19) lib/beaver/mlir/pass/composer.ex:79: anonymous fn/3 in Beaver.MLIR.Pass.Composer.add_pass/2
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (beaver 0.2.19) lib/beaver/mlir/pass/composer.ex:78: Beaver.MLIR.Pass.Composer.add_pass/2
    (beaver 0.2.19) lib/beaver/mlir/pass/composer.ex:98: anonymous fn/3 in Beaver.MLIR.Pass.Composer.to_pm/1
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:21: (file)
```

**Comment by glyh** [comment]
I also tried hexdoc article [here](jjhttps://hexdocs.pm/beaver/your-first-beaver-compiler.html), it doesn't work off REPL directly if I copy paste the code.

**Comment by jackalcooper** [comment]
check out this PR: https://github.com/beaver-lodge/beaver/pull/197/files

**Comment by glyh** [comment]
Thank you!
